import type { Planet } from '@/types/planet';

export const PLANETS: Planet[] = [
  {
    id: '1',
    name: 'Planet of Education',
    slug: 'education',
    description: 'Fostering knowledge and learning through workshops, seminars, and educational programs.',
    icon: '/images/planet_of_education.png',
    color: '#7DD3FC', // Unified accent
    director: {
      id: 'd1',
      name: 'Director Name',
      role: 'director',
      image: '/images/team/education-director.jpg',
      email: 'education.director@usjastro.lk',
      bio: 'Leading the educational initiatives of the astronomy club.',
    },
    managers: [
      {
        id: 'm1',
        name: 'Manager 1',
        role: 'manager',
        image: '/images/team/education-manager-1.jpg',
        email: 'manager1.education@usjastro.lk',
      },
      {
        id: 'm2',
        name: 'Manager 2',
        role: 'manager',
        image: '/images/team/education-manager-2.jpg',
        email: 'manager2.education@usjastro.lk',
      },
      {
        id: 'm3',
        name: 'Manager 3',
        role: 'manager',
        image: '/images/team/education-manager-3.jpg',
        email: 'manager3.education@usjastro.lk',
      },
    ],
    responsibilities: [
      'Organize astronomy workshops and seminars',
      'Conduct training sessions for members',
      'Develop educational content and resources',
      'Coordinate with academic institutions',
    ],
  },
  {
    id: '2',
    name: 'Planet of Research',
    slug: 'research',
    description: 'Advancing astronomical research and fostering scientific curiosity among members.',
    icon: '/images/planet_of_research.png',
    color: '#7DD3FC', // Unified accent
    director: {
      id: 'd2',
      name: 'Director Name',
      role: 'director',
      image: '/images/team/research-director.jpg',
      email: 'research.director@usjastro.lk',
      bio: 'Leading research initiatives and projects.',
    },
    managers: [
      {
        id: 'm4',
        name: 'Manager 1',
        role: 'manager',
        image: '/images/team/research-manager-1.jpg',
        email: 'manager1.research@usjastro.lk',
      },
      {
        id: 'm5',
        name: 'Manager 2',
        role: 'manager',
        image: '/images/team/research-manager-2.jpg',
        email: 'manager2.research@usjastro.lk',
      },
      {
        id: 'm6',
        name: 'Manager 3',
        role: 'manager',
        image: '/images/team/research-manager-3.jpg',
        email: 'manager3.research@usjastro.lk',
      },
    ],
    responsibilities: [
      'Conduct astronomical research projects',
      'Collaborate with research institutions',
      'Publish research findings',
      'Mentor students in research methodologies',
    ],
  },
  {
    id: '3',
    name: 'Planet of Media & Marketing',
    slug: 'media-marketing',
    description: 'Managing club communications, social media presence, and promotional activities.',
    icon: '/images/planet_of_media.png',
    color: '#7DD3FC', // Unified accent
    director: {
      id: 'd3',
      name: 'Director Name',
      role: 'director',
      image: '/images/team/media-director.jpg',
      email: 'media.director@usjastro.lk',
      bio: 'Managing media relations and marketing strategies.',
    },
    managers: [
      {
        id: 'm7',
        name: 'Manager 1',
        role: 'manager',
        image: '/images/team/media-manager-1.jpg',
        email: 'manager1.media@usjastro.lk',
      },
      {
        id: 'm8',
        name: 'Manager 2',
        role: 'manager',
        image: '/images/team/media-manager-2.jpg',
        email: 'manager2.media@usjastro.lk',
      },
      {
        id: 'm9',
        name: 'Manager 3',
        role: 'manager',
        image: '/images/team/media-manager-3.jpg',
        email: 'manager3.media@usjastro.lk',
      },
    ],
    responsibilities: [
      'Manage social media accounts',
      'Create promotional content',
      'Design marketing materials',
      'Handle public relations',
    ],
  },
  {
    id: '4',
    name: 'Planet of Management & Finance',
    slug: 'management-finance',
    description: 'Overseeing financial operations, budgeting, and administrative management.',
    icon: '/images/planet_of_management.png',
    color: '#7DD3FC', // Unified accent
    director: {
      id: 'd4',
      name: 'Director Name',
      role: 'director',
      image: '/images/team/management-director.jpg',
      email: 'management.director@usjastro.lk',
      bio: 'Overseeing financial and administrative operations.',
    },
    managers: [
      {
        id: 'm10',
        name: 'Manager 1',
        role: 'manager',
        image: '/images/team/management-manager-1.jpg',
        email: 'manager1.management@usjastro.lk',
      },
      {
        id: 'm11',
        name: 'Manager 2',
        role: 'manager',
        image: '/images/team/management-manager-2.jpg',
        email: 'manager2.management@usjastro.lk',
      },
      {
        id: 'm12',
        name: 'Manager 3',
        role: 'manager',
        image: '/images/team/management-manager-3.jpg',
        email: 'manager3.management@usjastro.lk',
      },
    ],
    responsibilities: [
      'Manage club finances and budgets',
      'Handle administrative tasks',
      'Coordinate resource allocation',
      'Maintain financial records',
    ],
  },
  {
    id: '5',
    name: 'Planet of Observation',
    slug: 'observation',
    description: 'Organizing stargazing sessions, telescope operations, and observational activities.',
    icon: '/images/planet_of_observation.png',
    color: '#7DD3FC', // Unified accent
    director: {
      id: 'd5',
      name: 'Director Name',
      role: 'director',
      image: '/images/team/observation-director.jpg',
      email: 'observation.director@usjastro.lk',
      bio: 'Leading observational activities and stargazing sessions.',
    },
    managers: [
      {
        id: 'm13',
        name: 'Manager 1',
        role: 'manager',
        image: '/images/team/observation-manager-1.jpg',
        email: 'manager1.observation@usjastro.lk',
      },
      {
        id: 'm14',
        name: 'Manager 2',
        role: 'manager',
        image: '/images/team/observation-manager-2.jpg',
        email: 'manager2.observation@usjastro.lk',
      },
      {
        id: 'm15',
        name: 'Manager 3',
        role: 'manager',
        image: '/images/team/observation-manager-3.jpg',
        email: 'manager3.observation@usjastro.lk',
      },
    ],
    responsibilities: [
      'Organize stargazing events',
      'Maintain and operate telescopes',
      'Plan observation sessions',
      'Document celestial observations',
    ],
  },
  {
    id: '6',
    name: 'Planet of Organizing',
    slug: 'organizing',
    description: 'Planning and executing club events, trips, and various activities.',
    icon: '/images/planet_of_organizing.png',
    color: '#7DD3FC', // Unified accent
    director: {
      id: 'd6',
      name: 'Director Name',
      role: 'director',
      image: '/images/team/organizing-director.jpg',
      email: 'organizing.director@usjastro.lk',
      bio: 'Coordinating events and organizational activities.',
    },
    managers: [
      {
        id: 'm16',
        name: 'Manager 1',
        role: 'manager',
        image: '/images/team/organizing-manager-1.jpg',
        email: 'manager1.organizing@usjastro.lk',
      },
      {
        id: 'm17',
        name: 'Manager 2',
        role: 'manager',
        image: '/images/team/organizing-manager-2.jpg',
        email: 'manager2.organizing@usjastro.lk',
      },
      {
        id: 'm18',
        name: 'Manager 3',
        role: 'manager',
        image: '/images/team/organizing-manager-3.jpg',
        email: 'manager3.organizing@usjastro.lk',
      },
    ],
    responsibilities: [
      'Plan and execute club events',
      'Organize astronomy trips',
      'Coordinate logistics for activities',
      'Manage event registrations',
    ],
  },
];
